twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
        - {name: twig.extension}