amazon:
  path: /dashboard/amazon
  methods: GET
  controller: App\Controller\AmazonController::show
  
amazonItemEdit:
  path: /dashboard/amazon/edit/{id}
  methods: GET
  controller: App\Controller\AmazonController::editAmazonItem