#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
  path: /logout
  methods: GET
login:
  path:     /login

app_ebay_item_show:
  path: /dashboard/ebay/item/{id}
  controller: App\Controller\EbayController::show

app_ebay_mark_as_shipped:
  path: /api/ebay/markshipped/{orderID}
  controller: App\Controller\OrdersController::markAsShipped
  methods: POST

app_ebay_unmark_shipped:
  path: /api/ebay/unmarkshipped/{orderID}
  controller: App\Controller\OrdersController::unmarkShipped
  methods: POST

app_ebay_leave_feedback:
  path: /api/ebay/leavefeedback/{transactionID}/{orderline}/{itemID}/{orderID}/{message}
  controller: App\Controller\OrdersController::leaveFeedback
  methods: POST

aliItemDescription:
  path: /dashboard/aliexpress/description/{id}
  methods: GET
  controller: App\Controller\AliExpressController::showDescription

aliItemEdit:
  path: /dashboard/aliexpress/edit/{id}
  methods: GET
  controller: App\Controller\AliExpressController::editAliExpressItem

aliExpress:
  path: /dashboard/aliexpress
  methods: GET
  controller: App\Controller\AliExpressController::show

aliExpressProduct:
  path: /dashboard/aliexpress
  methods: POST
  controller: App\Controller\AliExpressController::index

aliExpressToEbay:
  path: /dashboard/aliexpress/ebay
  methods: POST
  controller: App\Controller\AliExpressController::aliExpressToEbay

app_ebay_account_profile:
  path: /dashboard/profile/ebay-settings
  controller: App\Controller\ProfileController::ebaySettings

app_ebay_sold_items_date:
  path: /api/ebay-generate
  controller: App\Controller\EbayStatisticsController::showMonthGraph
  methods: GET

app_ebay_sold_items_profit:
  path: dashboard/api/ebay/month-profit
  controller: App\Controller\EbayStatisticsController::showMonthGraphProfit
  methods: GET

