#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
  path: /logout
  methods: GET
login:
  path:     /login

app_ebay_item_show:
  path: /dashboard/ebay/item/{id}
  controller: App\Controller\EbayController::show

app_ebay_mark_as_shipped:
  path: /api/ebay/markshipped/{orderID}
  controller: App\Controller\OrdersController::markAsShipped
  methods: POST

app_ebay_unmark_shipped:
  path: /api/ebay/unmarkshipped/{orderID}
  controller: App\Controller\OrdersController::unmarkShipped
  methods: POST

aliItemDescription:
  path: /dashboard/aliexpress/description/{id}
  methods: GET
  controller: App\Controller\AliExpressController::showDescription

aliItemEdit:
  path: /dashboard/aliexpress/edit/{id}
  methods: GET
  controller: App\Controller\AliExpressController::editAliExpressItem

aliExpress:
  path: /dashboard/aliexpress
  methods: GET
  controller: App\Controller\AliExpressController::show

aliExpressProduct:
  path: /dashboard/aliexpress
  methods: POST
  controller: App\Controller\AliExpressController::index

aliExpressToEbay:
  path: /dashboard/aliexpress/ebay
  methods: POST
  controller: App\Controller\AliExpressController::aliExpressToEbay
