#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
  path: /logout
  methods: GET
login:
  path:     /login
app_ebay_item_show:
  path: /dashboard/ebay/item/{id}
  controller: App\Controller\EbayController::show
